# Esfandiar Kiani (40311614) - ML - HM04.5

## Imports

In [5]:
import numpy as np
import pandas as pd
import matplotlib as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

## Read dataset

In [1]:
FILE_PATH = "D:/M.A/T1/ML/Assignments/HW4_SVM  Kernel/sonar_csv.csv"

In [9]:
df = pd.read_csv(FILE_PATH)

In [10]:
df.head()

attribute_1  attribute_2  attribute_3  attribute_4  attribute_5  \
0       0.0200       0.0371       0.0428       0.0207       0.0954   
1       0.0453       0.0523       0.0843       0.0689       0.1183   
2       0.0262       0.0582       0.1099       0.1083       0.0974   
3       0.0100       0.0171       0.0623       0.0205       0.0205   
4       0.0762       0.0666       0.0481       0.0394       0.0590   

   attribute_6  attribute_7  attribute_8  attribute_9  attribute_10  ...  \
0       0.0986       0.1539       0.1601       0.3109        0.2111  ...   
1       0.2583       0.2156       0.3481       0.3337        0.2872  ...   
2       0.2280       0.2431       0.3771       0.5598        0.6194  ...   
3       0.0368       0.1098       0.1276       0.0598        0.1264  ...   
4       0.0649       0.1209       0.2467       0.3564        0.4459  ...   

   attribute_52  attribute_53  attribute_54  attribute_55  attribute_56  \
0        0.0027        0.0065        0.0159        0.0072        0.0167   
1        0.0084        0.0089        0.0048        0.0094        0.0191   
2        0.0232        0.0166        0.0095        0.0180        0.0244   
3        0.0121        0.0036        0.0150        0.0085        0.0073   
4        0.0031        0.0054        0.0105        0.0110        0.0015   

   attribute_57  attribute_58  attribute_59  attribute_60  Class  
0        0.0180        0.0084        0.0090        0.0032   Rock  
1        0.0140        0.0049        0.0052        0.0044   Rock  
2        0.0316        0.0164        0.0095        0.0078   Rock  
3        0.0050        0.0044        0.0040        0.0117   Rock  
4        0.0072        0.0048        0.0107        0.0094   Rock  

[5 rows x 61 columns]

## Split data & label

In [12]:
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

In [15]:
X

array([[0.02  , 0.0371, 0.0428, ..., 0.0084, 0.009 , 0.0032],
       [0.0453, 0.0523, 0.0843, ..., 0.0049, 0.0052, 0.0044],
       [0.0262, 0.0582, 0.1099, ..., 0.0164, 0.0095, 0.0078],
       ...,
       [0.0522, 0.0437, 0.018 , ..., 0.0138, 0.0077, 0.0031],
       [0.0303, 0.0353, 0.049 , ..., 0.0079, 0.0036, 0.0048],
       [0.026 , 0.0363, 0.0136, ..., 0.0036, 0.0061, 0.0115]])

In [16]:
y

array(['Rock', 'Rock', 'Rock', 'Rock', 'Rock', 'Rock', 'Rock', 'Rock',
       'Rock', 'Rock', 'Rock', 'Rock', 'Rock', 'Rock', 'Rock', 'Rock',
       'Rock', 'Rock', 'Rock', 'Rock', 'Rock', 'Rock', 'Rock', 'Rock',
       'Rock', 'Rock', 'Rock', 'Rock', 'Rock', 'Rock', 'Rock', 'Rock',
       'Rock', 'Rock', 'Rock', 'Rock', 'Rock', 'Rock', 'Rock', 'Rock',
       'Rock', 'Rock', 'Rock', 'Rock', 'Rock', 'Rock', 'Rock', 'Rock',
       'Rock', 'Rock', 'Rock', 'Rock', 'Rock', 'Rock', 'Rock', 'Rock',
       'Rock', 'Rock', 'Rock', 'Rock', 'Rock', 'Rock', 'Rock', 'Rock',
       'Rock', 'Rock', 'Rock', 'Rock', 'Rock', 'Rock', 'Rock', 'Rock',
       'Rock', 'Rock', 'Rock', 'Rock', 'Rock', 'Rock', 'Rock', 'Rock',
       'Rock', 'Rock', 'Rock', 'Rock', 'Rock', 'Rock', 'Rock', 'Rock',
       'Rock', 'Rock', 'Rock', 'Rock', 'Rock', 'Rock', 'Rock', 'Rock',
       'Rock', 'Mine', 'Mine', 'Mine', 'Mine', 'Mine', 'Mine', 'Mine',
       'Mine', 'Mine', 'Mine', 'Mine', 'Mine', 'Mine', 'Mine', 'Mine',
      

## Covert labels into nums

In [17]:
y = LabelEncoder().fit_transform(y)

In [18]:
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Standardization

In [19]:
X = StandardScaler().fit_transform(X)

In [20]:
X

array([[-0.39955135, -0.04064823, -0.02692565, ...,  0.06987027,
         0.17167808, -0.65894689],
       [ 0.70353822,  0.42163039,  1.05561832, ..., -0.47240644,
        -0.44455424, -0.41985233],
       [-0.12922901,  0.60106749,  1.72340448, ...,  1.30935987,
         0.25276128,  0.25758223],
       ...,
       [ 1.00438083,  0.16007801, -0.67384349, ...,  0.90652575,
        -0.03913824, -0.67887143],
       [ 0.04953255, -0.09539176,  0.13480381, ..., -0.00759783,
        -0.70402047, -0.34015415],
       [-0.13794908, -0.06497869, -0.78861924, ..., -0.6738235 ,
        -0.29860448,  0.99479044]])

## Train/Test Split

In [28]:
random = 13
results = []

In [22]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.2, random_state= random)

## Model

### Linear

#### Model

In [31]:
linear_model = SVC(kernel= 'linear', random_state= random)

#### Trainning

In [25]:
linear_model.fit(X_train, y_train)

SVC(kernel='linear', random_state=13)

#### Evaluation

In [29]:
linear_train_acc = accuracy_score(y_train, linear_model.predict(X_train))
linear_test_acc = accuracy_score(y_test, linear_model.predict(X_test))
results.append(['Linear', linear_train_acc, linear_test_acc])

In [30]:
results

[['Linear', 0.927710843373494, 0.8571428571428571]]

### Polynomial

#### Model

In [33]:
poly_model = SVC(kernel= 'poly', random_state= random)

#### Trainning

In [34]:
poly_model.fit(X_train, y_train)

SVC(kernel='poly', random_state=13)

#### Eval

In [35]:
poly_train_acc = accuracy_score(y_train, poly_model.predict(X_train))
poly_test_acc = accuracy_score(y_test, poly_model.predict(X_test))
results.append(['Polynomial', poly_train_acc, poly_test_acc])

In [36]:
results

[['Linear', 0.927710843373494, 0.8571428571428571],
 ['Polynomial', 0.9879518072289156, 0.8333333333333334]]

### RBF

#### Model

In [37]:
rbf_model = SVC(kernel= 'rbf', random_state= random)

#### Train

In [38]:
rbf_model.fit(X_train, y_train)

SVC(random_state=13)

#### Eval

In [39]:
rbf_train_acc = accuracy_score(y_train, rbf_model.predict(X_train))
rbf_test_acc = accuracy_score(y_test, rbf_model.predict(X_test))
results.append(['RBF', rbf_train_acc, rbf_test_acc])

In [40]:
results

[['Linear', 0.927710843373494, 0.8571428571428571],
 ['Polynomial', 0.9879518072289156, 0.8333333333333334],
 ['RBF', 0.9759036144578314, 0.9285714285714286]]

### Plot the result

In [44]:
results_df = pd.DataFrame(results, columns=[
    'Kernel type', 'Train Set Classification Acc',
    'Test Set Classification Acc'
])

In [45]:
print(results_df)

  Kernel type  Train Set Classification Acc  Test Set Classification Acc
0      Linear                      0.927711                     0.857143
1  Polynomial                      0.987952                     0.833333
2         RBF                      0.975904                     0.928571
